services:
  veemee:
    image: ghcr.io/destinationhome/game-veemee:latest
    restart: unless-stopped
    user: "1002:1002"
    volumes:
      - /srv/destinationhome/public/veemee/public:/app/public
      - /srv/destinationhome/private/veemee/static:/app/static
      - /srv/destinationhome/private/veemee/data:/app/data
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://172.17.0.1:4318
    ports:
      - "30081:3000"
